# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from myprocess/process_points.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import sensor_msgs.msg

class process_points(genpy.Message):
  _md5sum = "803bf268be6fc471c9857ee901f96556"
  _type = "myprocess/process_points"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """sensor_msgs/PointCloud2 src_points
sensor_msgs/PointCloud2 tgt_points
sensor_msgs/PointCloud2 res_points
================================================================================
MSG: sensor_msgs/PointCloud2
# This message holds a collection of N-dimensional points, which may
# contain additional information such as normals, intensity, etc. The
# point data is stored as a binary blob, its layout described by the
# contents of the "fields" array.

# The point cloud data may be organized 2d (image-like) or 1d
# (unordered). Point clouds organized as 2d images may be produced by
# camera depth sensors such as stereo or time-of-flight.

# Time of sensor data acquisition, and the coordinate frame ID (for 3d
# points).
Header header

# 2D structure of the point cloud. If the cloud is unordered, height is
# 1 and width is the length of the point cloud.
uint32 height
uint32 width

# Describes the channels and their layout in the binary data blob.
PointField[] fields

bool    is_bigendian # Is this data bigendian?
uint32  point_step   # Length of a point in bytes
uint32  row_step     # Length of a row in bytes
uint8[] data         # Actual point data, size is (row_step*height)

bool is_dense        # True if there are no invalid points

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: sensor_msgs/PointField
# This message holds the description of one point entry in the
# PointCloud2 message format.
uint8 INT8    = 1
uint8 UINT8   = 2
uint8 INT16   = 3
uint8 UINT16  = 4
uint8 INT32   = 5
uint8 UINT32  = 6
uint8 FLOAT32 = 7
uint8 FLOAT64 = 8

string name      # Name of field
uint32 offset    # Offset from start of point struct
uint8  datatype  # Datatype enumeration, see above
uint32 count     # How many elements in the field
"""
  __slots__ = ['src_points','tgt_points','res_points']
  _slot_types = ['sensor_msgs/PointCloud2','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       src_points,tgt_points,res_points

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(process_points, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.src_points is None:
        self.src_points = sensor_msgs.msg.PointCloud2()
      if self.tgt_points is None:
        self.tgt_points = sensor_msgs.msg.PointCloud2()
      if self.res_points is None:
        self.res_points = sensor_msgs.msg.PointCloud2()
    else:
      self.src_points = sensor_msgs.msg.PointCloud2()
      self.tgt_points = sensor_msgs.msg.PointCloud2()
      self.res_points = sensor_msgs.msg.PointCloud2()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.src_points.header.seq, _x.src_points.header.stamp.secs, _x.src_points.header.stamp.nsecs))
      _x = self.src_points.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.src_points.height, _x.src_points.width))
      length = len(self.src_points.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.src_points.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.src_points.is_bigendian, _x.src_points.point_step, _x.src_points.row_step))
      _x = self.src_points.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.src_points.is_dense, _x.tgt_points.header.seq, _x.tgt_points.header.stamp.secs, _x.tgt_points.header.stamp.nsecs))
      _x = self.tgt_points.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.tgt_points.height, _x.tgt_points.width))
      length = len(self.tgt_points.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.tgt_points.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.tgt_points.is_bigendian, _x.tgt_points.point_step, _x.tgt_points.row_step))
      _x = self.tgt_points.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.tgt_points.is_dense, _x.res_points.header.seq, _x.res_points.header.stamp.secs, _x.res_points.header.stamp.nsecs))
      _x = self.res_points.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.res_points.height, _x.res_points.width))
      length = len(self.res_points.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.res_points.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.res_points.is_bigendian, _x.res_points.point_step, _x.res_points.row_step))
      _x = self.res_points.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.res_points.is_dense))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.src_points is None:
        self.src_points = sensor_msgs.msg.PointCloud2()
      if self.tgt_points is None:
        self.tgt_points = sensor_msgs.msg.PointCloud2()
      if self.res_points is None:
        self.res_points = sensor_msgs.msg.PointCloud2()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.src_points.header.seq, _x.src_points.header.stamp.secs, _x.src_points.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.src_points.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.src_points.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.src_points.height, _x.src_points.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.src_points.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.src_points.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.src_points.is_bigendian, _x.src_points.point_step, _x.src_points.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.src_points.is_bigendian = bool(self.src_points.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.src_points.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.src_points.is_dense, _x.tgt_points.header.seq, _x.tgt_points.header.stamp.secs, _x.tgt_points.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.src_points.is_dense = bool(self.src_points.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tgt_points.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.tgt_points.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.tgt_points.height, _x.tgt_points.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tgt_points.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.tgt_points.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.tgt_points.is_bigendian, _x.tgt_points.point_step, _x.tgt_points.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.tgt_points.is_bigendian = bool(self.tgt_points.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.tgt_points.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.tgt_points.is_dense, _x.res_points.header.seq, _x.res_points.header.stamp.secs, _x.res_points.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.tgt_points.is_dense = bool(self.tgt_points.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.res_points.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.res_points.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.res_points.height, _x.res_points.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.res_points.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.res_points.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.res_points.is_bigendian, _x.res_points.point_step, _x.res_points.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.res_points.is_bigendian = bool(self.res_points.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.res_points.data = str[start:end]
      start = end
      end += 1
      (self.res_points.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.res_points.is_dense = bool(self.res_points.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.src_points.header.seq, _x.src_points.header.stamp.secs, _x.src_points.header.stamp.nsecs))
      _x = self.src_points.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.src_points.height, _x.src_points.width))
      length = len(self.src_points.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.src_points.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.src_points.is_bigendian, _x.src_points.point_step, _x.src_points.row_step))
      _x = self.src_points.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.src_points.is_dense, _x.tgt_points.header.seq, _x.tgt_points.header.stamp.secs, _x.tgt_points.header.stamp.nsecs))
      _x = self.tgt_points.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.tgt_points.height, _x.tgt_points.width))
      length = len(self.tgt_points.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.tgt_points.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.tgt_points.is_bigendian, _x.tgt_points.point_step, _x.tgt_points.row_step))
      _x = self.tgt_points.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.tgt_points.is_dense, _x.res_points.header.seq, _x.res_points.header.stamp.secs, _x.res_points.header.stamp.nsecs))
      _x = self.res_points.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.res_points.height, _x.res_points.width))
      length = len(self.res_points.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.res_points.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.res_points.is_bigendian, _x.res_points.point_step, _x.res_points.row_step))
      _x = self.res_points.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.res_points.is_dense))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.src_points is None:
        self.src_points = sensor_msgs.msg.PointCloud2()
      if self.tgt_points is None:
        self.tgt_points = sensor_msgs.msg.PointCloud2()
      if self.res_points is None:
        self.res_points = sensor_msgs.msg.PointCloud2()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.src_points.header.seq, _x.src_points.header.stamp.secs, _x.src_points.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.src_points.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.src_points.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.src_points.height, _x.src_points.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.src_points.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.src_points.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.src_points.is_bigendian, _x.src_points.point_step, _x.src_points.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.src_points.is_bigendian = bool(self.src_points.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.src_points.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.src_points.is_dense, _x.tgt_points.header.seq, _x.tgt_points.header.stamp.secs, _x.tgt_points.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.src_points.is_dense = bool(self.src_points.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tgt_points.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.tgt_points.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.tgt_points.height, _x.tgt_points.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tgt_points.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.tgt_points.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.tgt_points.is_bigendian, _x.tgt_points.point_step, _x.tgt_points.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.tgt_points.is_bigendian = bool(self.tgt_points.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.tgt_points.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.tgt_points.is_dense, _x.res_points.header.seq, _x.res_points.header.stamp.secs, _x.res_points.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.tgt_points.is_dense = bool(self.tgt_points.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.res_points.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.res_points.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.res_points.height, _x.res_points.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.res_points.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.res_points.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.res_points.is_bigendian, _x.res_points.point_step, _x.res_points.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.res_points.is_bigendian = bool(self.res_points.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.res_points.data = str[start:end]
      start = end
      end += 1
      (self.res_points.is_dense,) = _get_struct_B().unpack(str[start:end])
      self.res_points.is_dense = bool(self.res_points.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IBI = None
def _get_struct_IBI():
    global _struct_IBI
    if _struct_IBI is None:
        _struct_IBI = struct.Struct("<IBI")
    return _struct_IBI
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
