(cl:defpackage myprocess-srv
  (:use )
  (:export
   "MYPROCESS_POSE"
   "<MYPROCESS_POSE-REQUEST>"
   "MYPROCESS_POSE-REQUEST"
   "<MYPROCESS_POSE-RESPONSE>"
   "MYPROCESS_POSE-RESPONSE"
   "MYPROCESS_POSITION"
   "<MYPROCESS_POSITION-REQUEST>"
   "MYPROCESS_POSITION-REQUEST"
   "<MYPROCESS_POSITION-RESPONSE>"
   "MYPROCESS_POSITION-RESPONSE"
  ))

